name: BUG报告
title: "[BUG] 请填写简短易读的标题"
description: "使用过程中遇到了BUG"
assignees: xiaoyaocz
labels:
  - "bug"
body:
  - type: checkboxes
    id: terms
    attributes:
      label: 非重复的Issue
      description: 先去Issues列表中查找下是否存在相似的Issue，如果有了就不要重复发了
      options:
        - label: 已确认没有相似的Issue
          required: true

  - type: textarea
    id: description
    validations:
      required: true
    attributes:
      label: BUG内容
      description: 请详细描述你遇到的问题

  - type: textarea
    id: steps
    validations:
      required: true
    attributes:
      label: 重现步骤
      render: plain text
      description: 请详细描述重现步骤
      placeholder: |
        1. xxxx
        2. xxxx
        3. xxxx

  - type: textarea
    id: screenshots
    attributes:
      label: 截图或视频
      description: 请上传BUG截图、或视频

  - type: textarea
    id: logs
    attributes:
      label: 日志
      description: 请上传日志文件
      placeholder: |
        可以在[其他设置]-[开启日志记录]后获取日志文件
 
  - type: input
    id: version
    attributes:
      label: 版本号
      description: 请填写你使用的APP版本号
      placeholder: ex. 1.0.1
    validations:
      required: true
 
  - type: dropdown
    id: release-type
    validations:
      required: true
    attributes:
      label: 使用版本
      description: 使用的是什么版本，从哪里下载的
      options:
        - 正式版(Releases)
        - 开发版(Actions)
      default: 0

  - type: dropdown
    id: platform
    validations:
      required: true
    attributes:
      label: 运行平台
      description: 选择你当前运行应用的平台
      multiple: false
      options:
        - Windows
        - macOS
        - Linux
        - Android
        - iOS
        - Android TV

  - type: input
    id: os-version
    attributes:
      label: 操作系统信息
      description: 请填写你的操作系统信息版本
      placeholder: ex. Windows 10 21H1 / MIUI 15 Android 12
    validations:
      required: true

  - type: input
    id: device
    attributes:
      label: 设备信息
      description: 请填写你的设备信息
      placeholder: ex. PC / iPhone 12 Pro Max
    validations:
      required: true

  - type: textarea
    id: remark
    attributes:
      label: 备注
      description: 其他信息
