name: simple_live_core
version: 1.0.3
description: "聚合直播核心库"
repository: https://github.com/xiaoyaocz/dart_simple_live
publish_to: "none"
environment: 
  sdk: '>=3.0.5 <4.0.0'

dependencies: 
  dio: ^5.5.0+1
  logger: ^2.4.0
  web_socket_channel: ^3.0.1
  html_unescape: ^2.0.0
  protobuf: ^3.1.0
  crypto: ^3.0.3
  brotli: ^0.6.0
  tars_dart:
    path: ./packages/tars_dart
  fixnum: ^1.1.0

dev_dependencies: 
  lints: ^2.0.0
  test: ^1.21.0

